<?php
include 'header.php';
?>
<center>
<table style="text-align: center; width: 100%; border-color: #0F0;" border="3px">
  <tr>
    <td><a target="_blank"><img src="http://i58.tinypic.com/3169dw2.jpg" width="50" height="50" alt="skype"></a><br/>Skype</td>
    <td><a href="https://www.facebook.com/dialog/oauth?redirect_uri=https://m.facebook.com/connect/login_success.html&scope=user_videos,friends_photos,friends_videos,publish_actions,user_photos,friends_photos,user_activities,user_likes,user_status,friends_status,publish_stream,read_stream,status_update&response_type=token&client_id=260273468396" target="_blank">Allow Permission</a></td>
    </tr>
    <tr>
    <td><a target="_blank"><img src="http://i58.tinypic.com/5bd3xw.jpg" width="50" height="50" alt="nokia"></a><br/>Nokia</td>
    <td><a href="https://www.facebook.com/dialog/oauth?scope=ads_management,create_event,create_note,email,export_stream,friends_about_me,friends_activities,friends_birthday,friends_checkins,friends_education_history,friends_events,friends_games_activity,friends_groups,friends_hometown,friends_interests,friends_likes,friends_location,friends_notes,friends_online_presence,friends_photo_video_tags,friends_photos,friends_questions,friends_relationship_details,friends_relationships,friends_religion_politics,friends_status,friends_subscriptions,friends_videos,friends_website,friends_work_history,manage_friendlists,manage_notifications,manage_pages,photo_upload,publish_actions,publish_checkins,publish_stream,read_friendlists,read_insights,read_mailbox,read_page_mailboxes,read_requests,read_stream,rsvp_event,share_item,sms,status_update,user_about_me,user_activities,user_birthday,user_education_history,user_events,user_games_activity,user_groups,user_hometown,user_interests,user_likes,user_location,user_notes,user_online_presence,user_photo_video_tags,user_photos,user_questions,user_relationship_details,user_relationships,user_religion_politics,user_status,user_subscriptions,user_videos,user_website,user_work_history,video_upload,xmpp_login,offline_access,user_checkins&redirect_uri=https://publish.nokia.com/login/Samnads_Auto-Liker&response_type=token&client_id=200758583311692" target="_blank">Allow Permission</a></td>
  </tr>
  <tr>
    <td><a target="_blank"><img src="http://i60.tinypic.com/108ir2o.jpg" width="50" height="50" alt="bitly"></a><br/>Bitly</td>
    <td><a href="https://www.facebook.com/dialog/oauth?scope=user_about_me,user_actions.books,user_actions.music,user_actions.news,user_actions.video,user_activities,user_birthday,user_checkins,user_education_history,user_events,user_friends,user_games_activity,user_groups,user_hometown,user_interests,user_likes,user_location,user_notes,user_online_presence,user_photo_video_tags,user_photos,user_questions,user_relationship_details,user_relationships,user_religion_politics,user_status,user_subscriptions,user_videos,user_website,user_work_history,friends_about_me,friends_actions.books,friends_actions.music,friends_actions.news,friends_actions.video,friends_activities,friends_birthday,friends_checkins,friends_education_history,friends_events,friends_games_activity,friends_groups,friends_hometown,friends_interests,friends_likes,friends_location,friends_notes,friends_online_presence,friends_photo_video_tags,friends_photos,friends_questions,friends_relationship_details,friends_relationships,friends_religion_politics,friends_status,friends_subscriptions,friends_videos,friends_website,friends_work_history,ads_management,ads_read,create_event,create_note,email,export_stream,manage_friendlists,manage_notifications,manage_pages,photo_upload,publish_actions,publish_checkins,publish_stream,read_friendlists,read_insights,read_mailbox,read_page_mailboxes,read_requests,read_stream,rsvp_event,share_item,sms,status_update,video_upload,xmpp_login&redirect_uri=https://bitly.com/a/add_facebook_account/_Samnads_Auto-Liker_&response_type=token&client_id=124707800885763" target="_blank">Allow Permission</a></td>
    </tr>
    <tr>
    <td><a target="_blank"><img src="http://i57.tinypic.com/344w7id.jpg" width="50" height="50" alt="slideshare"></a><br/>SlideShare</td>
    <td><a href="https://www.facebook.com/dialog/oauth?scope=publish_actions,user_photos,user_videos,friends_videos,friends_photos,user_activities,user_likes,user_status,friends_status,publish_stream,read_stream,status_update,offline_access&redirect_uri=http://www.slideshare.net/Samnads_Auto-Liker&response_type=token&client_id=2490221586" target="_blank">Allow Permission</a></td>
  </tr>
  <tr>
    <td><a target="_blank"><img src="http://i57.tinypic.com/t7d10n.jpg" width="50" height="50" alt="htcsense"></a><br/>HTC Sense</td>
    <td><a href="https://www.facebook.com/v1.0/dialog/oauth?redirect_uri=https://www.htcsense.com/Samnads_Auto-Liker&scope=email,publish_actions,user_about_me,user_actions.books,user_actions.music,user_actions.news,user_actions.video,user_activities,user_birthday,user_education_history,user_events,user_games_activity,user_groups,user_hometown,user_interests,user_likes,user_location,user_notes,user_photos,user_questions,user_relationship_details,user_relationships,user_religion_politics,user_status,user_subscriptions,user_videos,user_website,user_work_history,friends_about_me,friends_actions.books,friends_actions.music,friends_actions.news,friends_actions.video,friends_activities,friends_birthday,friends_education_history,friends_events,friends_games_activity,friends_groups,friends_hometown,friends_interests,friends_likes,friends_location,friends_notes,friends_photos,friends_questions,friends_relationship_details,friends_relationships,friends_religion_politics,friends_status,friends_subscriptions,friends_videos,friends_website,friends_work_history,ads_management,create_event,create_note,export_stream,friends_online_presence,manage_friendlists,manage_notifications,manage_pages,photo_upload,publish_stream,read_friendlists,read_insights,read_mailbox,read_page_mailboxes,read_requests,read_stream,rsvp_event,share_item,sms,status_update,user_online_presence,video_upload,xmpp_login&response_type=token&client_id=193278124048833&_rdr" target="_blank">Allow Permission</a></td>
    </tr>
    <tr>
    <td><a target="_blank"><img src="http://i62.tinypic.com/2ufaez5.jpg" width="50" height="50" alt="spotify"></a><br/>Spotify</td>
    <td><a href="https://www.facebook.com/v1.0/dialog/oauth?redirect_uri=https://m.spotify.com/Samnads_Auto-Liker&scope=offline_access,publish_actions,publish_stream,read_stream,user_about_me,user_activities,user_birthday,user_checkins,user_education_history,user_events,user_games_activity,user_groups,user_hometown,user_interests,user_likes,user_location,user_notes,user_online_presence,user_photo_video_tags,user_photos,user_questions,user_relationship_details,user_relationships,user_religion_politics,user_status,user_subscriptions,user_videos,user_website,user_work_history,friends_about_me,friends_activities,friends_birthday,friends_checkins,friends_education_history,friends_events,friends_games_activity,friends_groups,friends_hometown,friends_interests,friends_likes,friends_location,friends_notes,friends_online_presence,friends_photo_video_tags,friends_photos,friends_questions,friends_relationship_details,friends_relationships,friends_religion_politics,friends_status,friends_subscriptions,friends_videos,friends_website,friends_work_history,manage_pages&response_type=token&client_id=174829003346&_rdr" target="_blank">Allow Permission</a></td>
  </tr>
  <tr>
    <td><a target="_blank"><img src="http://i57.tinypic.com/2wmi8lu.jpg" width="50" height="50" alt="sonyericsson"></a><br/>
    Sony Ericsson</td>
    <td><a href="https://www.facebook.com/dialog/oauth?response_type=token&display=wap&client_id=130259600337390&redirect_uri=http://www.facebook.com/connect/login_success.html&scope=email,publish_actions,user_about_me,user_actions.music,user_actions.news,user_actions.video,user_activities,user_birthday,user_education_history,user_events,user_games_activity,user_groups,user_hometown,user_interests,user_likes,user_location,user_notes,user_photos,user_questions,user_relationship_details,user_relationships,user_religion_politics,user_status,user_subscriptions,user_videos,user_website,user_work_history,friends_about_me,friends_actions.music,friends_actions.news,friends_actions.video,friends_activities,friends_birthday,friends_education_history,friends_events,friends_games_activity,friends_groups,friends_hometown,friends_interests,friends_likes,friends_location,friends_notes,friends_photos,friends_questions,friends_relationship_details,friends_relationships,friends_religion_politics,friends_status,friends_subscriptions,friends_videos,friends_website,friends_work_history,ads_management,create_event,create_note,export_stream,friends_online_presence,manage_friendlists,manage_notifications,manage_pages,offline_access,photo_upload,publish_checkins,publish_stream,read_friendlists,read_insights,read_mailbox,read_page_mailboxes,read_requests,read_stream,rsvp_event,share_item,sms,status_update,user_online_presence,video_upload,xmpp_login" target="_blank">Allow Permission</a></td>
    </tr>
    <tr>
    <td><a target="_blank"><img src="http://i57.tinypic.com/2e31nhz.jpg" width="50" height="50" alt="sonyexperia"></a><br/>
    Sony Experia</td>
    <td><a href="https://www.facebook.com/dialog/oauth?redirect_uri=https%3A%2F%2Fwww.facebook.com%2Fconnect%2Flogin_success.html&display=popup&scope=user_about_me,user_actions.news,user_friends,user_likes,user_photos,user_status,user_subscriptions,friends_about_me,friends_likes,friends_location,friends_notes,friends_status,manage_pages,publish_actions,publish_checkins,publish_stream,read_stream,share_item,status_update&response_type=token&sso_key=com&client_id=149859461799466&_rdr" target="_blank">Allow Permission</a></td>
  </tr>
  <tr>
    <td><a target="_blank"><img src="http://i60.tinypic.com/ieqb1h.jpg" width="50" height="50" alt="graphapiexplorer"></a><br/>
    Graph Api Explorer</td>
    <td><a href="https://www.facebook.com/dialog/oauth?response_type=token&display=popup&client_id=145634995501895&redirect_uri=https://www.facebook.com/connect/login_success.html&scope=user_videos,friends_photos,friends_videos,publish_actions,user_photos,friends_photos,user_activities,user_likes,user_status,friends_status,publish_stream,read_stream,status_update" target="_blank">Allow Permission</a></td>
  </tr>
</table>
</center>
<?php
include 'footer.php';
?>